spring:
  application:
    name: Deposito
  datasource:
    url: jdbc:h2:~/depositoapi
    password: 
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /banco

